In [1]:
import pandas as pd
import numpy as np
import dtale

In [13]:
benefit_csv=pd.read_csv(r"C:\Users\nithi\Downloads\capstone project\Capstone_project-git\benefits-and-cost-sharing-puf\benefits-and-cost-sharing-puf.csv")
benefit_csv.head(5)

C:\Users\nithi\AppData\Local\Temp\ipykernel_5948\988571510.py:1: DtypeWarning:

Columns (9,12,19) have mixed types. Specify dtype option on import or set low_memory=False.

,BusinessYear,StateCode,IssuerId,SourceName,ImportDate,StandardComponentId,PlanId,BenefitName,CopayInnTier1,CopayInnTier2,...,IsEHB,IsCovered,QuantLimitOnSvc,LimitQty,LimitUnit,Exclusions,Explanation,EHBVarReason,IsExclFromInnMOOP,IsExclFromOonMOOP
0,2024,AK,21989,HIOS,2023-12-08 01:02:13,21989AK0030001,21989AK0030001-00,Routine Dental Services (Adult),Not Applicable,NaN,...,NaN,Covered,Yes,1100.0,Dollars per Year,NaN,See policy for other limits,Not EHB,Yes,Yes
1,2024,AK,21989,HIOS,2023-12-08 01:02:13,21989AK0030001,21989AK0030001-00,Dental Check-Up for Children,Not Applicable,NaN,...,Yes,Covered,NaN,NaN,NaN,NaN,See policy for limits,Substantially Equal,No,No
2,2024,AK,21989,HIOS,2023-12-08 01:02:13,21989AK0030001,21989AK0030001-00,Basic Dental Care - Child,Not Applicable,NaN,...,Yes,Covered,NaN,NaN,NaN,NaN,See policy for limits,NaN,No,No
3,2024,AK,21989,HIOS,2023-12-08 01:02:13,21989AK0030001,21989AK0030001-00,Orthodontia - Child,Not Applicable,NaN,...,Yes,Covered,NaN,NaN,NaN,NaN,For medically necessary only,Substantially Equal,No,No
4,2024,AK,21989,HIOS,2023-12-08 01:02:13,21989AK0030001,21989AK0030001-00,Major Dental Care - Child,Not Applicable,NaN,...,Yes,Covered,NaN,NaN,NaN,NaN,See policy for limits,NaN,No,No

In [4]:
benefit_csv.columns

Index(['BusinessYear', 'StateCode', 'IssuerId', 'SourceName', 'ImportDate',
       'StandardComponentId', 'PlanId', 'BenefitName', 'CopayInnTier1',
       'CopayInnTier2', 'CopayOutofNet', 'CoinsInnTier1', 'CoinsInnTier2',
       'CoinsOutofNet', 'IsEHB', 'IsCovered', 'QuantLimitOnSvc', 'LimitQty',
       'LimitUnit', 'Exclusions', 'Explanation', 'EHBVarReason',
       'IsExclFromInnMOOP', 'IsExclFromOonMOOP'],
      dtype='object')

In [3]:
benefit_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1849555 entries, 0 to 1849554
Data columns (total 24 columns):
 #   Column               Dtype
---  ------               -----
 0   BusinessYear         int64
 1   StateCode            object
 2   IssuerId             int64
 3   SourceName           object
 4   ImportDate           object
 5   StandardComponentId  object
 6   PlanId               object
 7   BenefitName          object
 8   CopayInnTier1        object
 9   CopayInnTier2        object
 10  CopayOutofNet        object
 11  CoinsInnTier1        object
 12  CoinsInnTier2        object
 13  CoinsOutofNet        object
 14  IsEHB                object
 15  IsCovered            object
 16  QuantLimitOnSvc      object
 17  LimitQty             float64
 18  LimitUnit            object
 19  Exclusions           object
 20  Explanation          object
 21  EHBVarReason         object
 22  IsExclFromInnMOOP    object
 23  IsExclFromOonMOOP    object
dtypes: float64(1), int64(2), object(21)
memory usage: 338.7+ MB

In [9]:
benefit_csv[['BusinessYear', 'StateCode']].drop_duplicates()

         BusinessYear StateCode
0                2024        AK
4990             2024        AL
23095            2024        AZ
103830           2024        FL
249466           2024        IN
283873           2024        LA
323288           2024        MO
379973           2024        MS
405148           2024        NC
501403           2024        ND
522973           2024        OK
583466           2024        SC
624993           2024        TN
695207           2024        TX
1016046          2024        WI
1171586          2024        WY
1180846          2024        AR
1205342          2024        DE
1225546          2024        GA
1311696          2024        HI
1317060          2024        IA
1346357          2024        IL
1488580          2024        KS
1523265          2024        MI
1585232          2024        MT
1617869          2024        NE
1653629          2024        NH
1688320          2024        OH
1755680          2024        OR
1782534          2024        SD
1806542          2024        UT
1837666          2024        WV

In [12]:
health_plan_col=pd. DataFrame(benefit_csv['BenefitName'].unique())
health_plan_col

In [ ]:
print("hello")